"""Measure stable pet hit envelopes from the shipped alpha masks, offline only."""
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ROWS = ['idle', 'running-right', 'running-left', 'waving', 'jumping',
        'failed', 'waiting', 'running', 'review']
BANDS = 24
registration_source = (ROOT / 'src/client/companion-registration.ts').read_text(encoding='utf-8')
REGISTRATION = json.loads(registration_source.split(' = ', 1)[1].strip().rstrip(';'))


def envelope_for(manifest, cell, sprite, masks, suffix=''):
    width, height = cell['width'], cell['height']
    union = np.zeros((height, width), dtype=bool)
    for alpha in masks:
        solid = alpha.point(lambda value: 255 if value >= 16 else 0).filter(ImageFilter.MaxFilter(5))
        union |= np.asarray(solid) > 0
    regions = []
    for band in range(BANDS):
        top, bottom = round(band * height / BANDS), round((band + 1) * height / BANDS)
        yy, xx = np.where(union[top:bottom])
        if len(xx):
            regions.append([int(xx.min()), top, int(xx.max() + 1 - xx.min()), bottom - top])
    covered = np.zeros_like(union)
    for x, y, w, h in regions:
        covered[y:y+h, x:x+w] = True
    assert not np.any(union & ~covered), 'Envelope must contain every measured frame'
    result = {'id': manifest['id'] + suffix, 'width': width, 'height': height,
              'columns': sprite.get('columns', 8), 'renderer': manifest['renderer'], 'regions': regions}
    return result, {'petId': result['id'], 'frames': len(masks), 'regions': len(regions),
                    'rectangleArea': width * height, 'envelopeArea': int(covered.sum()),
                    'reductionPercent': round(100 * (1 - covered.mean()), 1)}


def measure(directory):
    manifest = json.loads((directory / 'pet.json').read_text(encoding='utf-8'))
    sprite = manifest.get('sprite2d', {})
    cell = sprite.get('cell', {'width': 192, 'height': 208})
    if manifest['renderer'] == 'frames2d':
        config = manifest['frames2d']
        idle = config.get('phases', {}).get('idle', 'idle')
        with Image.open(directory / config['dir'] / idle / config['tracks'][idle]['frames'][0]) as first:
            cell = {'width': first.width, 'height': first.height}
    width, height = cell['width'], cell['height']
    tracks = {}
    if manifest['renderer'] == 'sprite2d':
        sheet = Image.open(directory / sprite['spritesheetPath']).convert('RGBA')
        for row, animation in enumerate(ROWS):
            track = sprite.get('tracks', {}).get(animation, {})
            for column in track.get('frames', range(sprite['frames'][row])):
                alpha = sheet.getchannel('A').crop((column * width, row * height,
                                                   (column + 1) * width, (row + 1) * height))
                dx, dy = REGISTRATION.get(manifest['id'], {}).get(animation, [[0, 0]])[column]
                registered = Image.new('L', (width, height))
                registered.paste(alpha, (dx, dy))
                tracks.setdefault(animation, []).append(registered)
    else:
        config = manifest['frames2d']
        for track, definition in config['tracks'].items():
            for filename in definition['frames']:
                alpha = Image.open(directory / config['dir'] / track / filename).convert('RGBA').getchannel('A')
                # Same centered object-fit:contain used by Frames2dVisualMount.
                fitted = ImageOps.contain(alpha, (width, height), Image.Resampling.LANCZOS)
                registered = Image.new('L', (width, height))
                registered.paste(fitted, ((width - fitted.width) // 2, (height - fitted.height) // 2))
                tracks.setdefault(track, []).append(registered)
    # Each pose uses a stable union of its frames, including gameplay tracks.
    frames = [alpha for masks in tracks.values() for alpha in masks]
    results = [envelope_for(manifest, cell, sprite, frames)]
    results.extend(envelope_for(manifest, cell, sprite, masks, ':' + track)
                   for track, masks in tracks.items())
    return results


if __name__ == '__main__':
    envelopes, report = {}, []
    for name in ['whale-refined', 'miku', 'blue-whale-business']:
        for envelope, stats in measure(ROOT / 'assets' / name):
            envelopes[envelope['id']] = envelope
            report.append(stats)
    target = ROOT / 'src/client/pet-hit-envelopes.generated.ts'
    target.write_text('// Generated by scripts/build-hit-envelopes.py; no runtime image scanning.\n'
                      'export const measuredPetEnvelopes = '
                      + json.dumps(envelopes, separators=(',', ':')) + ' as const\n', encoding='utf-8')
    output = ROOT / 'output/bubble-interaction-verification'
    output.mkdir(parents=True, exist_ok=True)
    (output / 'hit-envelopes.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    print(json.dumps([entry for entry in report if ':' not in entry['petId'] or entry['petId'].endswith(':idle')]))
